<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ClientType;

class ClientTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clientTypes = [
            [
                'name' => 'Agente Immobiliare',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Titolare Autonomo o Contitolare',
                'purpose' => 'Collaborazione per l\'istruttoria di mutui ipotecari legati a compravendite immobiliari.',
                'data_subjects' => 'Clienti (Acquirenti/Richiedenti mutuo)',
                'data_categories' => 'Anagrafici, Contatto, Documenti Identità, Dati dell\'immobile',
                'retention_period' => '10 anni dall\'erogazione (obblighi AML/Civilistici) o 12 mesi se respinta.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Scambio documenti tramite piattaforme sicure/CRM, crittografia allegati.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Commercialista / Esperto Contabile',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Titolare Autonomo',
                'purpose' => 'Acquisizione documentazione reddituale e fiscale per l\'istruttoria di finanziamenti aziendali o personali.',
                'data_subjects' => 'Clienti, Amministratori, Soci, Titolari Effettivi',
                'data_categories' => 'Anagrafici, Documenti Identità, Dati Economici e Finanziari (Bilanci, Unico, CUD)',
                'retention_period' => '10 anni dalla chiusura del rapporto.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Accesso limitato per competenza, invio tramite PEC o portale sicuro.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Consulente del Lavoro',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Responsabile Esterno / Titolare Autonomo',
                'purpose' => 'Acquisizione certificazioni stipendiali e TFR per pratiche di Cessione del Quinto e Prestiti Personali.',
                'data_subjects' => 'Clienti (Dipendenti)',
                'data_categories' => 'Anagrafici, Documenti Identità, Dati Economici (Buste paga, Certificati di stipendio)',
                'retention_period' => '10 anni dall\'estinzione del finanziamento.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Scambio dati cifrato, password protection sui PDF.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Consulente Aziendale',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Responsabile Esterno',
                'purpose' => 'Supporto tecnico per redazione Business Plan e richieste di credito Corporate.',
                'data_subjects' => 'Clienti (Amministratori, Garanti)',
                'data_categories' => 'Anagrafici, Dati Economici e Finanziari (Piani industriali, flussi di cassa, CRIF)',
                'retention_period' => '10 anni dalla chiusura della pratica.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Accordo di riservatezza (NDA), accessi segregati al CRM.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Assicuratore',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Titolare Autonomo o Responsabile Esterno',
                'purpose' => 'Emissione polizze CPI (Credit Protection Insurance) collegate all\'erogazione del credito.',
                'data_subjects' => 'Clienti (Assicurati)',
                'data_categories' => 'Anagrafici, Economici, Categorie Particolari (Dati sanitari, questionari anamnestici)',
                'retention_period' => '10 anni dalla scadenza della polizza.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Buste chiuse per dati sanitari, archivi ad accesso ristretto ai soli incaricati.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Procacciatore d\'Affari',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Responsabile Esterno / Incaricato',
                'purpose' => 'Segnalazione di nominativi interessati a prodotti di credito (Lead Generation).',
                'data_subjects' => 'Potenziali Clienti (Prospect)',
                'data_categories' => 'Anagrafici, Contatto',
                'retention_period' => '24 mesi per finalità commerciali (o fino a revoca del consenso).',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Formazione privacy obbligatoria, divieto di conservazione locale dei dati.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Concessionario Auto',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Responsabile Esterno o Contitolare',
                'purpose' => 'Istruttoria per prestiti finalizzati all\'acquisto di veicoli e Leasing targato.',
                'data_subjects' => 'Clienti (Acquirenti)',
                'data_categories' => 'Anagrafici, Documenti Identità, Economici (Preventivi, IBAN, Reddito base)',
                'retention_period' => '10 anni dall\'erogazione.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Caricamento diretto a portale, divieto di fotocopie non custodite.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Call Center (Telemarketing / Qualifica Lead)',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Responsabile Esterno (Art. 28)',
                'purpose' => 'Contatto telefonico per pre-qualifica commerciale e fissazione appuntamenti.',
                'data_subjects' => 'Potenziali Clienti e Clienti in portafoglio',
                'data_categories' => 'Anagrafici, Contatto, Dati Economici di base',
                'retention_period' => 'Max 12 mesi per lead non convertiti, 24 mesi per marketing con consenso.',
                'extra_eu_transfer' => 'Possibile (Verificare sede server dialer)',
                'security_measures' => 'Sistemi di masking del numero telefonico, divieto di export database.',
                'privacy_data' => null,
            ],
            [
                'name' => 'List Provider (Fornitore Liste Contatti)',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Titolare Autonomo',
                'purpose' => 'Acquisizione liste anagrafiche consensate per campagne di marketing diretto.',
                'data_subjects' => 'Potenziali Clienti (Prospect)',
                'data_categories' => 'Anagrafici, Contatto',
                'retention_period' => 'Fino a revoca del consenso o opt-out.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Verifica preventiva della validità dei consensi (Audit fornitori).',
                'privacy_data' => null,
            ],
            [
                'name' => 'Software House (Sviluppo Gestionale / CRM)',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Responsabile Esterno (Art. 28)',
                'purpose' => 'Sviluppo, manutenzione, assistenza tecnica e hosting del gestionale pratiche cloud.',
                'data_subjects' => 'Tutti (Clienti, Prospect, Collaboratori, Dipendenti)',
                'data_categories' => 'TUTTI (Anagrafici, Identità, Economici, Sanitari, Minori, Log di navigazione)',
                'retention_period' => 'Per tutta la durata del contratto SaaS + 30 giorni per distruzione backup.',
                'extra_eu_transfer' => 'Sì/No (Dipende dal provider cloud).',
                'security_measures' => 'Crittografia at-rest e in-transit (TLS), ISO 27001, Backup immutabili.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Consulente Informatico / Sistemista (Gestione Server/Rete)',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Amministratore di Sistema / Responsabile Esterno',
                'purpose' => 'Gestione infrastruttura hardware/software, reti LAN, backup e disaster recovery.',
                'data_subjects' => 'Clienti, Dipendenti',
                'data_categories' => 'Dati di Navigazione, Log di Sistema, IP, Accesso incidentale ai database in chiaro.',
                'retention_period' => 'Log di sistema conservati per almeno 6 mesi.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Autenticazione a due fattori (2FA) obbligatoria, tracciamento log amministratori.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Avvocato',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Titolare Autonomo',
                'purpose' => 'Gestione pratiche di Saldo e Stralcio, esdebitamento, o istruttoria in presenza di contenziosi.',
                'data_subjects' => 'Clienti, Controparti, Creditori',
                'data_categories' => 'Anagrafici, Economici, Categorie Particolari (Dati giudiziari, sentenze)',
                'retention_period' => '10 anni dalla definizione della vertenza.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Segreto professionale, archivi fisici e digitali protetti.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Notaio',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Titolare Autonomo',
                'purpose' => 'Stipula atti pubblici per mutui, surroghe, costituzione garanzie ipotecarie e procure.',
                'data_subjects' => 'Clienti (Richiedenti, Datori di ipoteca)',
                'data_categories' => 'Anagrafici, Documenti Identità, Dati Economico-Finanziari e Patrimoniali',
                'retention_period' => 'Illimitata per gli atti a rogito / 10 anni per documenti in possesso del Mediatore.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Canali crittografati dedicati (Rete Nazionale Notariato).',
                'privacy_data' => null,
            ],
            [
                'name' => 'Perito Immobiliare',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Responsabile Esterno o Titolare Autonomo',
                'purpose' => 'Sopralluogo e redazione perizia estimativa dell\'immobile a garanzia del finanziamento.',
                'data_subjects' => 'Clienti (Proprietari/Acquirenti)',
                'data_categories' => 'Anagrafici, Contatti, Dati catastali, Planimetrie',
                'retention_period' => '10 anni dalla redazione della perizia.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Invio perizie tramite portali bancari sicuri o file protetti da password.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Amministratore di Condominio',
                'is_person' => true,
                'is_company' => true,
                'privacy_role' => 'Titolare Autonomo',
                'purpose' => 'Fornitura documentazione per istruttoria finanziamenti destinati a lavori condominiali.',
                'data_subjects' => 'Condòmini',
                'data_categories' => 'Anagrafici, Economico-Finanziari (Ripartizione millesimale, delibere)',
                'retention_period' => '10 anni.',
                'extra_eu_transfer' => 'No',
                'security_measures' => 'Comunicazione limitata ai soli dati pertinenti alla pratica di finanziamento.',
                'privacy_data' => null,
            ],
            [
                'name' => 'Dipendente Pubblico',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Dipendente Privato',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Pensionato',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Privato Consumatore',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Autonomo',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Ditta Individuale',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Libero Professionista',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Amministratore',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Titolare',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
            [
                'name' => 'Socio',
                'is_person' => false,
                'is_company' => false,
                'privacy_role' => null,
                'purpose' => null,
                'data_subjects' => null,
                'data_categories' => null,
                'retention_period' => null,
                'extra_eu_transfer' => null,
                'security_measures' => null,
                'privacy_data' => null,
            ],
        ];

        foreach ($clientTypes as $type) {
            ClientType::create($type);
        }
    }
}
